#!/bin/bash

ENV_FILE="$HOME/.config/system-vars/vars.env"

update_variable() {
    local KEY=$1
    local VALUE=$2

    if grep -q "^export $KEY=" "$ENV_FILE"; then
        sed -i "s|^export $KEY=.*|export $KEY=\"$VALUE\"|" "$ENV_FILE"
    else
        echo "export $KEY=\"$VALUE\"" >> "$ENV_FILE"
    fi

    dbus-send --session --type=signal \
              /com//Config \
              com..Config.Updated \
              string:"$KEY" string:"$VALUE"
}

GEO_DATA=$(curl -s https://ipinfo.io/json)

if [ $? -eq 0 ]; then
    ZIP_VAL=$(echo "$GEO_DATA" | jq -r '.postal')
    LOC_VAL=$(echo "$GEO_DATA" | jq -r '.loc')

    if [ "$ZIP_VAL" != "null" ]; then
        update_variable "ZIP" "$ZIP_VAL"
    fi

    if [ "$LOC_VAL" != "null" ]; then
        update_variable "LOC" "$LOC_VAL"
    fi
else
    echo "Error: Failed to fetch geolocation data."
    exit 1
fi

if [ ! -z "$1" ] && [ ! -z "$2" ]; then
    update_variable "$1" "$2"
fi